---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://github.com/mcostabile/aws-ecs.git
    targetRevision: HEAD
    path: ecs
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

