---

apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: develop
spec:
  forProvider:
    clusterName: develop-cluster
    region: us-west-1
    capacityProviders:
    - FARGATE
    - FARGATE_SPOT
    tags:
    - key: Type
      value: develop
  providerConfigRef:
    name: develop
