apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: cluster-control-pc-node
  annotations:
    crossplane.io/external-name: sg-001e48eb299a55221
spec:
  forProvider:
    description: Security Group for wordpress
    groupName: cluster-control-pc-node
    region: us-west-1
  providerConfigRef:
    name: develop