apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: develop
spec:
  forProvider:
    description: Cluster communication with worker nodes
    groupName: develop-sg
    ingress:
      - fromPort: 80
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
        toPort: 80
    region: us-west-1
    vpcIdRef:
      name: vpc-control-pc
  providerConfigRef:
    name: develop