apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  name: test-targetgroup-with-ip-target
spec:
  forProvider:
    name: test-targetgroup-with-ip-target
    port: 80
    protocol: HTTP
    region: us-west-1
    targetType: ip
    vpcIdRef:
      name: vpc-control-pc
  providerConfigRef:
    name: develop