apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: vpc-control-pc
  annotations: 
    crossplane.io/external-name: vpc-0775fcc19ec3f0248
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 10.210.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: develop

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: vpc-control-pc-private-us-west-1c
spec:
  forProvider: 
    cidrBlock: 10.210.2.0/24
  providerConfigRef:
    name: develop

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: vpc-control-pc-private-us-west-1b
spec:
  forProvider:
    cidrBlock: 10.210.3.0/24
  providerConfigRef:
    name: develop